[project]
name = "camera-raw-test"
version = "0.1.0"
description = "Raw tester for Sony star-eater"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10.1",
    "pyqt6>=6.9.0",
    "rawpy>=0.24.0",
]
